name: Deploy to Unikraft

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Unikraft CLI
        uses: unikraft/setup-action@v1

      - name: Login to Unikraft Cloud
        run: printf '%s' "${{ secrets.UNIKRAFT_TOKEN }}" | unikraft login --token -

      - name: Run instance
        run: unikraft run --metro sin -p 443:8080/http+tls -m 512M --image "${{ secrets.UNIKRAFT_ORG }}/singbox:latest" -- /usr/local/bin/sing-box run -c /etc/sing-box/config.json
